### ISSUE TITLE
列表信息流样式弹幕使用

### ISSUE THREAD

**Issue by hanliangel** [KwaiAppTeam/AkDanmaku#11]
请问在信息流的样式下，不同视频的弹幕数据源切换，是靠不同的DanmakuPlayer对象来区分么，每一个视频都需要new一个新的DanmakuPlayer对象吗？

**Comment by xanahopper** [comment]
是的，DanmakuPlayer 就是被设计为一个与源绑定的、one shot 形式的 Player
