### ISSUE TITLE
发送弹幕重叠时候 如何在之前弹幕上面

### ISSUE THREAD

**Issue by weakup** [KwaiAppTeam/AkDanmaku#13]
现在发送的弹幕 可能在上面也可能在下面

**Comment by xanahopper** [comment]
弹幕的垂直位置取决于 Layouter 的实现，目前默认的 Layouter 实现并不会刻意要求在上方或下方
从 TopLayouter 而言，是从上寻找第一个能够容纳它高度的空间。
如果希望固定的、特别的布局规律，请自行实现或扩展 Layouter
