### ISSUE TITLE
生成的用户头像不能针对每条弹幕单独定制吗？怎么都是整体设置的

### ISSUE THREAD

**Issue by hepiao3** [KwaiAppTeam/AkDanmaku#25]
private val renderer by lazy {
    TypedDanmakuRenderer(
      simpleRenderer,
      DanmakuItemData.DANMAKU_STYLE_USER_AVATAR to UpLogoRenderer(
        ResourcesCompat.getDrawable(resources, R.drawable.icon_danmaku_input_text_up_icon, theme)!!
      )
    )
  }
相当于这个DanmaPlayer都得用这个user_avatar，不是应该不同的弹幕各自设置自己的icon吗？
每次自己发送弹幕时，设置的danmakuStyle使用的icon都是事先设置好的

**Comment by xanahopper** [comment]
DanmakuItemData 可以自定义自己的类，拿到之后可以获取到自己的数据

**Comment by hepiao3** [comment]
感谢点拨，我自己自定义了一个AvatarRenderer，其中的drawable不再初始化DanmakuPlayer传入renderer时就设置，而是在解析json updatItem时先加载icon，加载成功后向DanmakuItem传入得到的drawable，最终AvatarRenderer measure和draw时拿取DanmaItem中的drawable进行测量绘制就可以了，这样每一条弹幕都能单独配置自己的Icon。
