### ISSUE TITLE
是否有计划提供DanmakuSurfaceView呢！

### ISSUE THREAD

**Issue by hepiao3** [KwaiAppTeam/AkDanmaku#26]
目前跟其它动效或者video运行起来，弹幕还不是很顺畅会卡view渲染。

**Comment by xanahopper** [comment]
SurfaceView 的透明问题很多，而且 OpenGL 环境涉及到和其他东西混合公用，所以暂不提供。
其实你想的话，可以把视频播放、其他 OpenGL 和弹幕结合起来
