### ISSUE TITLE
建议更改成java

### ISSUE THREAD

**Issue by ag2s20150909** [KwaiAppTeam/AkDanmaku#4]
1，用kotlin写库没有特殊处理，用纯java写的应用无法使用，kotlin在吸血java.
2,  Kotlin语言的API变化频繁，高版本与低版本大概率不兼容。
3，Kotlin写的应用除了写的方便，编译时间，运行效率，应用大小都不如java.

**Comment by purofle** [comment]
迷惑

**Comment by changyiZ** [comment]
Kotlin vs Java 的对比没必要再次讨论了，但是 Android 官方将 Kotlin 已经作为 primary language，所以 - 细品吧
